### ISSUE TITLE
Watch 3rd party IP issues

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/demand-capacity-mgmt#52]
## Description

The frontend does have some 3rd party libs, that are not yet IP/Licence cleared.
I created the IP issues via dash-licences tool.

Please monitor the following issues:

- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13090
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13091
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13092
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13093
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13094

If concluded successfully, update the `DEPENDENCIES_FRONTEND` file again

__EDIT:__ Additional issues after switch to `npm`

- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13095
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13096
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13097
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13098
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13099
- [x] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13100

**Comment by SebastianBezold** [comment]
The issues before where created based on the `yarn.lock` file, which has been removed in the meantime in favor of the `package-lock.json`.
However, `npm install` does not work without `--legacy-peer-deps` as option. Doing so resulted in even more libs that have to be reviewed by dash and the EF license compliance team. Adding them to the list in the description

**Comment by Bailonis** [comment]
Waiting for this two:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13092
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13099

**Comment by SebastianBezold** [comment]
Both remaining open issues resolved
