### ISSUE TITLE
Clarify react-native usage

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/demand-capacity-mgmt#65]
There is an open 3rd party IP issue, where clarification is needed. 
See [the issue comment](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13099#note_1890000).

I am wondering, where and why we need react-native, since I was under the impression, that we are building a webapp only.

FYI @ClosedSourcerer

**Comment by SebastianBezold** [comment]
Hi @ClosedSourcerer,

I cannot find any usage of react-naitive components. I also cannot find any hint in the commit, that added the react-native dependency initially. See [commit](https://github.com/eclipse-tractusx/demand-capacity-mgmt/commit/f052d0aaa54d218948cf9b7133f98c616c9f39bc#diff-e88f0ab710e414e1a4dbe119204df9c8dcc673b63fb90706095d08912df74631R34)

When removing the dependency from the list, I can at least build the app locally. Unfortunately there seem to be no tests, that could further verify that. Could you please find someone, who can verify, if this dependency can be removed without issues?

**Comment by ClosedSourcerer** [comment]
@SebastianBezold 

I contacted to original authors. We should get a qualified answer within a week.

**Comment by SebastianBezold** [comment]
Hi @ClosedSourcerer,

did you already receive feedback from the original authors?
I don't want to keep the EF ticket open for too long. If we cannot get an answer, I could also remove the dependency for now and leave the testing for someone picking up development in the future

**Comment by ClosedSourcerer** [comment]
@SebastianBezold
 
Not yet, I upgrade this to an weekly escalation cycle.

**Comment by SebastianBezold** [comment]
HI @Ruskyy, thanks for the update. Then I'll remove the lib and let the EF know on the 3rd party IP issue.

**Comment by SebastianBezold** [comment]
Removed in [ab322a8](https://github.com/eclipse-tractusx/demand-capacity-mgmt/commit/ab322a825cc968d84f01b84f026aa1067e1f3c07)
